#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import regex

# 0x2D (0045), 0x96 (0150), 0x97 (0151), 0xAD (0173)
DASHES = "-–—­"
RESCAPE_DASHES = regex.escape(DASHES)
RE_DASHES_VARIANTS = r"[%s]" % DASHES

_STR_NAMES_SEPARATORS = " ,\u200b" + DASHES
RESCAPE_NAMES_SEPARATORS = regex.escape(_STR_NAMES_SEPARATORS)
RE_NAMES_SEPARATORS = r"[%s]" % RESCAPE_NAMES_SEPARATORS
RE_NOT_SEPARATORS = r"[^%s]" % RESCAPE_NAMES_SEPARATORS
